USE [master]
GO

/****** Object:  Database [scrilla.js] ******/
CREATE DATABASE [scrilla.js] ON  PRIMARY 
( NAME = N'scrilla.js', FILENAME = N'D:\DATA\scrilla.js.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'scrilla.js_log', FILENAME = N'D:\DATA\scrilla.js.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [scrilla.js] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [scrilla.js].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [scrilla.js] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [scrilla.js] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [scrilla.js] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [scrilla.js] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [scrilla.js] SET ARITHABORT OFF 
GO

ALTER DATABASE [scrilla.js] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [scrilla.js] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [scrilla.js] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [scrilla.js] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [scrilla.js] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [scrilla.js] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [scrilla.js] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [scrilla.js] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [scrilla.js] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [scrilla.js] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [scrilla.js] SET  DISABLE_BROKER 
GO

ALTER DATABASE [scrilla.js] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [scrilla.js] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [scrilla.js] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [scrilla.js] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [scrilla.js] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [scrilla.js] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [scrilla.js] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [scrilla.js] SET  READ_WRITE 
GO

ALTER DATABASE [scrilla.js] SET RECOVERY FULL 
GO

ALTER DATABASE [scrilla.js] SET  MULTI_USER 
GO

ALTER DATABASE [scrilla.js] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [scrilla.js] SET DB_CHAINING OFF 
GO




-- create login
GO
USE [master]

IF NOT EXISTS 
    (SELECT name  
     FROM master.sys.server_principals
     WHERE name = 'IIS AppPool\scrilla.js.Web')
BEGIN
    CREATE LOGIN [IIS AppPool\scrilla.js.Web] FROM WINDOWS WITH DEFAULT_DATABASE=[scrilla.js]
END

-- create user
GO
USE [scrilla.js]

IF NOT EXISTS
    (SELECT name
     FROM sys.database_principals
     WHERE name = 'IIS AppPool\scrilla.js.Web')
BEGIN
    CREATE USER [IIS AppPool\scrilla.js.Web] FOR LOGIN [IIS AppPool\scrilla.js.Web] 
	EXEC sp_addrolemember N'db_owner', N'IIS AppPool\scrilla.js.Web'
END
