// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static class MVC
{
    public static scrilla.js.Web.Controllers.ScrillaController Scrilla = new scrilla.js.Web.Controllers.T4MVC_ScrillaController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class app {
        private const string URLPATH = "~/app";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string app_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/app.min.js") ? Url("app.min.js") : Url("app.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class controllers {
            private const string URLPATH = "~/app/controllers";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string AccountController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/AccountController.min.js") ? Url("AccountController.min.js") : Url("AccountController.js");
            public static readonly string AccountController_min_js = Url("AccountController.min.js");
            public static readonly string AccountController_min_js_map = Url("AccountController.min.js.map");
            public static readonly string TransactionController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/TransactionController.min.js") ? Url("TransactionController.min.js") : Url("TransactionController.js");
            public static readonly string TransactionController_min_js = Url("TransactionController.min.js");
            public static readonly string TransactionController_min_js_map = Url("TransactionController.min.js.map");
            public static readonly string VendorController_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/VendorController.min.js") ? Url("VendorController.min.js") : Url("VendorController.js");
            public static readonly string VendorController_min_js = Url("VendorController.min.js");
            public static readonly string VendorController_min_js_map = Url("VendorController.min.js.map");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class directives {
            private const string URLPATH = "~/app/directives";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string dateRangeSlider_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dateRangeSlider.min.js") ? Url("dateRangeSlider.min.js") : Url("dateRangeSlider.js");
            public static readonly string dateRangeSlider_min_js = Url("dateRangeSlider.min.js");
            public static readonly string dateRangeSlider_min_js_map = Url("dateRangeSlider.min.js.map");
            public static readonly string summary_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/summary.min.js") ? Url("summary.min.js") : Url("summary.js");
            public static readonly string summary_min_js = Url("summary.min.js");
            public static readonly string summary_min_js_map = Url("summary.min.js.map");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class filters {
            private const string URLPATH = "~/app/filters";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string duringMonthsFilter_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/duringMonthsFilter.min.js") ? Url("duringMonthsFilter.min.js") : Url("duringMonthsFilter.js");
            public static readonly string duringMonthsFilter_min_js = Url("duringMonthsFilter.min.js");
            public static readonly string duringMonthsFilter_min_js_map = Url("duringMonthsFilter.min.js.map");
            public static readonly string parenlessCurrencyFilter_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/parenlessCurrencyFilter.min.js") ? Url("parenlessCurrencyFilter.min.js") : Url("parenlessCurrencyFilter.js");
            public static readonly string parenlessCurrencyFilter_min_js = Url("parenlessCurrencyFilter.min.js");
            public static readonly string parenlessCurrencyFilter_min_js_map = Url("parenlessCurrencyFilter.min.js.map");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class services {
            private const string URLPATH = "~/app/services";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string AccountService_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/AccountService.min.js") ? Url("AccountService.min.js") : Url("AccountService.js");
            public static readonly string AccountService_min_js = Url("AccountService.min.js");
            public static readonly string AccountService_min_js_map = Url("AccountService.min.js.map");
            public static readonly string DateRangeService_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/DateRangeService.min.js") ? Url("DateRangeService.min.js") : Url("DateRangeService.js");
            public static readonly string DateRangeService_min_js = Url("DateRangeService.min.js");
            public static readonly string DateRangeService_min_js_map = Url("DateRangeService.min.js.map");
            public static readonly string TransactionService_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/TransactionService.min.js") ? Url("TransactionService.min.js") : Url("TransactionService.js");
            public static readonly string TransactionService_min_js = Url("TransactionService.min.js");
            public static readonly string TransactionService_min_js_map = Url("TransactionService.min.js.map");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class styles {
            private const string URLPATH = "~/app/styles";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string app_less = Url("app.less");
            public static readonly string app_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/app.min.css") ? Url("app.min.css") : Url("app.css");
                 
            public static readonly string app_css_map = Url("app.css.map");
            public static readonly string app_min_css = Url("app.min.css");
            public static readonly string bootstrap_theme_less = Url("bootstrap-theme.less");
            public static readonly string bootstrap_theme_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap-theme.min.css") ? Url("bootstrap-theme.min.css") : Url("bootstrap-theme.css");
                 
            public static readonly string bootstrap_theme_css_map = Url("bootstrap-theme.css.map");
            public static readonly string bootstrap_theme_min_css = Url("bootstrap-theme.min.css");
            public static readonly string jqRangeSlider_less = Url("jqRangeSlider.less");
            public static readonly string jqRangeSlider_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jqRangeSlider.min.css") ? Url("jqRangeSlider.min.css") : Url("jqRangeSlider.css");
                 
            public static readonly string jqRangeSlider_css_map = Url("jqRangeSlider.css.map");
            public static readonly string jqRangeSlider_min_css = Url("jqRangeSlider.min.css");
            public static readonly string ngGrid_less = Url("ngGrid.less");
            public static readonly string ngGrid_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/ngGrid.min.css") ? Url("ngGrid.min.css") : Url("ngGrid.css");
                 
            public static readonly string ngGrid_min_css = Url("ngGrid.min.css");
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class views {
            private const string URLPATH = "~/app/views";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string accounts_html = Url("accounts.html");
            public static readonly string transactions_html = Url("transactions.html");
            public static readonly string vendors_html = Url("vendors.html");
        }
    
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class Scripts {}
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class Styles {}
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        //string path = VirtualPathUtility.ToAbsolute(virtualPath);
		string path = VirtualPathUtility.ToAppRelative(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591


